CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE whoohoo (
 id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
 apn VARCHAR,
 object_id INTEGER,
 license_number VARCHAR,
 category VARCHAR,
 milestone VARCHAR,
 tier VARCHAR,
 status VARCHAR,
 issue_date TIMESTAMPTZ,
 expiration_date TIMESTAMPTZ,
 address VARCHAR,
 owner_name VARCHAR,
 owner_address_1 VARCHAR,
 owner_address_2 VARCHAR,
 owner_city VARCHAR,
 owner_state VARCHAR,
 owner_zip VARCHAR,
 owner_phone VARCHAR,
 owner_email VARCHAR,
 applicant_name VARCHAR,
 applicant_address_1 VARCHAR,
 applicant_address_2 VARCHAR,
 applicant_city VARCHAR,
 applicant_state VARCHAR,
 applicant_zip VARCHAR,
 applicant_phone VARCHAR,
 applicant_email VARCHAR,
 licensed_units INTEGER,
 ward VARCHAR,
 neighborhood_desc VARCHAR,
 community_desc VARCHAR,
 police_precinct VARCHAR,
 latitude DOUBLE PRECISION,
 longitude DOUBLE PRECISION,
 x_web_mercator DOUBLE PRECISION,
 y_web_mercator DOUBLE PRECISION
);